version: '3.1'

services: 
  app: 
    build: ./bot
    restart: always
    environment:
      - BOT_TOKEN=YOUR_BOT_TOKEN
      - TELEGRAM_ACCESS=YOUR_USERID
    ports:
      - '5555:5000' 
    depends_on: 
      - db
    volumes:
      - ./bot:/app

  db:
    image: postgres
    container_name: server_database
    restart: always
    environment:
      POSTGRES_DB: name_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'

volumes:
    postgres_data:
