version: '3.1'

services: 
  app: 
    image: artbvr/botfi:2.0
    restart: always
    environment:
      - BOT_TOKEN=YOUR_BOT_TOKEN
      - TELEGRAM_ACCESS=YOUR_USERID
    ports:
      - '5555:5000' 
    depends_on: 
      - db

  db:
    image: postgres
    container_name: server_database
    restart: always
    environment:
      POSTGRES_DB: finbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 17da89zh
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'

volumes:
    postgres_data:
